exp_name: objaverse-ablations-sft-bothdirection
output_dir: "./runs"
dataset_dir: "./data"
category: "objaverse-renderings"
dataset_kwargs: 
  winning_strategy: "random_by_threshold"
  sample_image_strategy: "uniform"
  temperature: 20
  hard_threshold: 20
  use_filtered_models: false
  num_images_per_prompt: 6
  num_models_per_image: 4
  sample_from_all_multiviews: true

batch_size: 12
learning_rate: 5.e-6
lr_warmup_steps: 2000
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
# adam_epsilon: 1.e-6
max_train_steps: 20000
max_grad_norm: 1.0
gradient_accumulation_steps: 1

use_sft: true

flow_matching_t_logit_normal_mu: 1.0
flow_matching_t_logit_normal_sigma: 1.0
dpo_beta: 500.0

log_interval: 10
ckpt_interval: 1000
seed: 0
logger_type: "wandb"

# resume_from_checkpoint: /home/ruiningli/TRELLIS/runs/objaverse-all-lr1e-5-hardthresh20-beta500-loraR64-weightdecay1e-2-sameeps-multiview_2025-02-20T09-46-41/checkpoint-0008000

use_lora: true
lora_r: 64
lora_alpha: 128
lora_dropout: 0.0
