exp_name: objaverse-unstable-overfit-lr5e-6-hardthresh20-beta2000-loraR16-weightdecay1e-1-CORRECT
output_dir: "./runs"
dataset_dir: "./data"
category: "objaverse"
dataset_kwargs: 
  winning_strategy: "random_by_threshold"
  sample_image_strategy: "uniform"
  temperature: 20
  hard_threshold: 20
  use_filtered_models: false
  num_images_per_prompt: 12
  # sample_from_all_multiviews: true
  # prompts: ["0224e1fb5bbb41a38d0b3d18aa58c607"]

batch_size: 6
learning_rate: 5.e-6
lr_warmup_steps: 500
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.1
# adam_epsilon: 1.e-6
max_train_steps: 6000
max_grad_norm: 1.0
gradient_accumulation_steps: 2
sample_same_epsilon: false

flow_matching_t_logit_normal_mu: 1.0
flow_matching_t_logit_normal_sigma: 1.0
dpo_beta: 2000.0

log_interval: 10
ckpt_interval: 1000
seed: 0
logger_type: "wandb"

# resume_from_checkpoint: /home/ruiningli/TRELLIS/runs/objaverse-unstable-overfit-lr5e-6-hardthresh20-beta2000-loraR16-weightdecay1e-1-sameeps_2025-02-13T09-49-55/checkpoint-0003500

use_lora: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.0
