# image_paths: /mnt/disks/data/physics-gen-eval/motorcycle-eval/*.jpg
image_paths: /mnt/disks/data/objaverse-flux-final/00053/000.jpg

# image_paths: /mnt/disks/data/flux-images/motorcycle/00510/*.jpg
# image_paths: /home/ruiningli/projects/eval-objaverse/objaverse/*/*.png
# image_paths: /mnt/disks/data/sim-DPO/clock/00003/*.jpg
# image_paths: ./data/clock-objs/*.jpg
use_original: true
sample_dir: ./samples/objaverse-original-method-visual-notexture
num_models_per_image: 16
naming_level: 1