image_paths: /mnt/disks/data/physics-gen-eval/motorcycle-eval/*.jpg

# image_paths: /mnt/disks/data/flux-images/motorcycle/00006/*.jpg
# image_paths: /mnt/disks/data/sim-DPO/clock/00003/*.jpg
# image_paths: ./data/clock-objs/*.jpg
# image_paths: /home/ruiningli/projects/eval-objaverse/objaverse/*/*.png

# ckpt_path: /home/ruiningli/TRELLIS/runs/objaverse-unstable-overfit-lr5e-6-hardthresh20-beta500-loraR64-weightdecay1e-2_2025-02-11T15-36-04/checkpoint-0006000/model.safetensors
# ckpt_path: /home/ruiningli/TRELLIS/runs/objaverse-all-lr5e-6-hardthresh20-beta500-loraR64-weightdecay1e-2-sameeps-multiview_2025-02-21T22-06-28/checkpoint-0008000/model.safetensors
# ckpt_path: /home/ruiningli/TRELLIS/runs/objaverse-ablations-sft_2025-03-03T23-44-56/checkpoint-0008000/model.safetensors
ckpt_path: /home/ruiningli/TRELLIS/runs/objaverse-ablations-dro_2025-03-05T19-19-11/checkpoint-0004000/model.safetensors
# ckpt_path: /home/ruiningli/TRELLIS/runs/objaverse-unstable-overfit-lr5e-6-hardthresh20-beta2000-loraR16-weightdecay1e-1_2025-02-12T11-33-46/checkpoint-0001000/model.safetensors
sample_dir: ./samples/objaverse-flux-dro-04000-ALLSTABLE
# sample_dir: /home/ruiningli/TRELLIS/samples/objaverse-eval-11obj-loraR16-hardthresh20-beta2000-wd1e-1-01000iters
# sample_dir: ./samples/original
num_models_per_image: 1
naming_level: 2